eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
spring:
  application:
    name: feign-client-consumer-hystrix
server:
  port: 9002
feign:
    hystrix:
      enabled: true
management.endpoints.web.exposure.include: hystrix.stream